version: '3.4'

services:

  vehicletrackingsystemdb:
    container_name: vehicletrackingsystemdb
    environment:
        SA_PASSWORD: "SwN12345678"
        ACCEPT_EULA: "Y"
    ports:
        - "1433:1433"

  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:VehicleTrackingSystemConnectionString=Server=vehicletrackingsystemdb;Database=VehicleTrackingSystemDb;User Id=sa;Password=SwN12345678"
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "8000:80"
      - "8001:443"
    depends_on:
      - vehicletrackingsystemdb
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro