version: '3.4'

services:

  vehicletrackingsystemdb:
    image: mcr.microsoft.com/mssql/server:2017-latest

  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: Source/Presentation/API/Dockerfile
